# Generated by Django 4.2.11 on 2025-09-08 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food', 'Food & Drinks'), ('transport', 'Transport'), ('bills', 'Bills & Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('health', 'Health & Fitness'), ('education', 'Education'), ('others', 'Others')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('m', 'Meter'), ('cm', 'Centimeter')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
